// <auto-generated />
using System;
using CNPM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNPM.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20260413051316_AddStatusToCustomer")]
    partial class AddStatusToCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNPM.Models.TblBaoCaoThuChi", b =>
                {
                    b.Property<string>("PkSMaBc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaBC");

                    b.Property<bool?>("BTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangThai");

                    b.Property<DateTime?>("DTgBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgBatDau");

                    b.Property<DateTime?>("DTgKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgKetThuc");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.HasKey("PkSMaBc")
                        .HasName("PK__tbl_BaoC__DF6E59A563C250A1");

                    b.HasIndex("FkSMaNv");

                    b.ToTable("tbl_BaoCaoThuChi");
                });

            modelBuilder.Entity("CNPM.Models.TblBienBanHuy", b =>
                {
                    b.Property<string>("PkSMaBbh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaBBH");

                    b.Property<bool?>("BTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangThai");

                    b.Property<DateTime?>("DTgBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgBatDau");

                    b.Property<DateTime?>("DTgKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgKetThuc");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.Property<string>("SDiaDiemHuy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sDiaDiemHuy");

                    b.Property<string>("SPhuongThucHuy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sPhuongThucHuy");

                    b.HasKey("PkSMaBbh")
                        .HasName("PK__tbl_Bien__471DAAF591300568");

                    b.HasIndex("FkSMaNv");

                    b.ToTable("tbl_BienBanHuy");
                });

            modelBuilder.Entity("CNPM.Models.TblBienBanKiemKe", b =>
                {
                    b.Property<string>("PkSMaBbk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaBBK");

                    b.Property<bool?>("BTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangThai");

                    b.Property<DateTime?>("DTgBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgBatDau");

                    b.Property<DateTime?>("DTgKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgKetThuc");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.Property<string>("SDiaDiemKiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sDiaDiemKiem");

                    b.HasKey("PkSMaBbk")
                        .HasName("PK__tbl_Bien__471DAAF09CB84A54");

                    b.HasIndex("FkSMaNv");

                    b.ToTable("tbl_BienBanKiemKe");
                });

            modelBuilder.Entity("CNPM.Models.TblChucVu", b =>
                {
                    b.Property<string>("PkSMaCv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaCV");

                    b.Property<string>("STenCv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTenCV");

                    b.HasKey("PkSMaCv")
                        .HasName("PK__tbl_Chuc__DF6FC22C02D5DE3B");

                    b.ToTable("tbl_ChucVu");
                });

            modelBuilder.Entity("CNPM.Models.TblCtbienBanHuy", b =>
                {
                    b.Property<string>("PkFkSMaBbh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaBBH");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISl")
                        .HasColumnType("int")
                        .HasColumnName("iSL");

                    b.Property<string>("SLyDo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sLyDo");

                    b.HasKey("PkFkSMaBbh", "PkFkSMaSp")
                        .HasName("PK__tbl_CTBi__11043D0062DDA535");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTBienBanHuy");
                });

            modelBuilder.Entity("CNPM.Models.TblCtbienBanKiemKe", b =>
                {
                    b.Property<string>("PkFkSMaBbk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaBBK");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISl")
                        .HasColumnType("int")
                        .HasColumnName("iSL");

                    b.HasKey("PkFkSMaBbk", "PkFkSMaSp")
                        .HasName("PK__tbl_CTBi__11043D051975011B");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTBienBanKiemKe");
                });

            modelBuilder.Entity("CNPM.Models.TblCthopDongCungCap", b =>
                {
                    b.Property<string>("PkFkSMaHd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaHD");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<double?>("FDonGia")
                        .HasColumnType("float")
                        .HasColumnName("fDonGia");

                    b.HasKey("PkFkSMaHd", "PkFkSMaSp")
                        .HasName("PK__tbl_CTHo__091C136FB51E64E6");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTHopDongCungCap");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuDatHang", b =>
                {
                    b.Property<string>("PkFkSMaPdh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaPDH");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISl")
                        .HasColumnType("int")
                        .HasColumnName("iSL");

                    b.HasKey("PkFkSMaPdh", "PkFkSMaSp")
                        .HasName("PK__tbl_CTPh__0520BA68D00B7CC9");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTPhieuDatHang");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuGiaoHang", b =>
                {
                    b.Property<string>("PkFkSMaPgh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaPGH");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISl")
                        .HasColumnType("int")
                        .HasColumnName("iSL");

                    b.HasKey("PkFkSMaPgh", "PkFkSMaSp")
                        .HasName("PK__tbl_CTPh__0520918C69F32167");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTPhieuGiaoHang");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuNhapKho", b =>
                {
                    b.Property<string>("PkFkSMaPn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaPN");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISl")
                        .HasColumnType("int")
                        .HasColumnName("iSL");

                    b.Property<string>("SGhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sGhiChu");

                    b.HasKey("PkFkSMaPn", "PkFkSMaSp")
                        .HasName("PK__tbl_CTPh__091D5C4B78BE2206");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTPhieuNhapKho");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuThu", b =>
                {
                    b.Property<string>("PkFkSMaPt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaPT");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISl")
                        .HasColumnType("int")
                        .HasColumnName("iSL");

                    b.HasKey("PkFkSMaPt", "PkFkSMaSp")
                        .HasName("PK__tbl_CTPh__091D5C3171E973FD");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTPhieuThu");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuXuatKho", b =>
                {
                    b.Property<string>("PkFkSMaPx")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaPX");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISlx")
                        .HasColumnType("int")
                        .HasColumnName("iSLX");

                    b.Property<int?>("ISlyc")
                        .HasColumnType("int")
                        .HasColumnName("iSLYC");

                    b.Property<string>("SGhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sGhiChu");

                    b.HasKey("PkFkSMaPx", "PkFkSMaSp")
                        .HasName("PK__tbl_CTPh__091D5C3573D4441B");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTPhieuXuatKho");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuYeuCau", b =>
                {
                    b.Property<string>("PkFkSMaPyc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaPYC");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.Property<int?>("ISlcan")
                        .HasColumnType("int")
                        .HasColumnName("iSLCan");

                    b.Property<int?>("ISlduyet")
                        .HasColumnType("int")
                        .HasColumnName("iSLDuyet");

                    b.HasKey("PkFkSMaPyc", "PkFkSMaSp")
                        .HasName("PK__tbl_CTPh__055C17A93C3EE7F8");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTPhieuYeuCau");
                });

            modelBuilder.Entity("CNPM.Models.TblHopDongCungCap", b =>
                {
                    b.Property<string>("PkSMaHd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaHD");

                    b.Property<DateTime?>("DNgayBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("dNgayBatDau");

                    b.Property<DateTime?>("DNgayKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("dNgayKetThuc");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNcc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNCC");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.HasKey("PkSMaHd")
                        .HasName("PK__tbl_HopD__DF6FAADA3738AE65");

                    b.HasIndex("FkSMaNcc");

                    b.HasIndex("FkSMaNv");

                    b.ToTable("tbl_HopDongCungCap");
                });

            modelBuilder.Entity("CNPM.Models.TblKhachHang", b =>
                {
                    b.Property<string>("PkSMaKh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaKH");

                    b.Property<bool?>("BTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangThai");

                    b.Property<DateTime?>("DNgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("dNgaySinh");

                    b.Property<string>("SDiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sDiaChi");

                    b.Property<string>("SSdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sSDT");

                    b.Property<string>("STenKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTenKH");

                    b.HasKey("PkSMaKh")
                        .HasName("PK__tbl_Khac__DF6E0330D00AA42B");

                    b.ToTable("tbl_KhachHang");
                });

            modelBuilder.Entity("CNPM.Models.TblLoaiSanPham", b =>
                {
                    b.Property<string>("PkSMaLoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaLoai");

                    b.Property<string>("STenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenLoai");

                    b.HasKey("PkSMaLoai")
                        .HasName("PK__tbl_Loai__5D93B0465D2093CB");

                    b.ToTable("tbl_LoaiSanPham");
                });

            modelBuilder.Entity("CNPM.Models.TblNhaCungCap", b =>
                {
                    b.Property<string>("PkSMaNcc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaNCC");

                    b.Property<string>("SDiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sDiaChi");

                    b.Property<string>("SSdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sSDT");

                    b.Property<string>("SSoTk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sSoTK");

                    b.Property<string>("STenNcc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenNCC");

                    b.HasKey("PkSMaNcc")
                        .HasName("PK__tbl_NhaC__7ADBE2FEB607D37E");

                    b.ToTable("tbl_NhaCungCap");
                });

            modelBuilder.Entity("CNPM.Models.TblNhanVien", b =>
                {
                    b.Property<string>("PkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaNV");

                    b.Property<bool?>("BTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangThai");

                    b.Property<DateTime?>("DNgaySinh")
                        .HasColumnType("datetime")
                        .HasColumnName("dNgaySinh");

                    b.Property<DateTime?>("DNgayVaoLam")
                        .HasColumnType("datetime")
                        .HasColumnName("dNgayVaoLam");

                    b.Property<string>("FkSMaCv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaCV");

                    b.Property<string>("FkSMaTk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaTK");

                    b.Property<string>("SCccd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sCCCD");

                    b.Property<string>("SHoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sHoTen");

                    b.Property<string>("SSdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sSDT");

                    b.HasKey("PkSMaNv")
                        .HasName("PK__tbl_Nhan__DF6FFB014FB56926");

                    b.HasIndex("FkSMaCv");

                    b.HasIndex("FkSMaTk");

                    b.ToTable("tbl_NhanVien");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuChi", b =>
                {
                    b.Property<string>("PkSMaPchi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaPChi");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.Property<string>("FkSMaPn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaPN");

                    b.Property<string>("SHinhThucTt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sHinhThucTT");

                    b.HasKey("PkSMaPchi")
                        .HasName("PK__tbl_Phie__5351DBF3ABB44345");

                    b.HasIndex("FkSMaNv");

                    b.HasIndex("FkSMaPn");

                    b.ToTable("tbl_PhieuChi");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuDatHang", b =>
                {
                    b.Property<string>("PkSMaPdh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaPDH");

                    b.Property<bool?>("BTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangThai");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.Property<string>("FkSMaPyc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaPYC");

                    b.HasKey("PkSMaPdh")
                        .HasName("PK__tbl_Phie__7A58168C837175E1");

                    b.HasIndex("FkSMaNv");

                    b.HasIndex("FkSMaPyc");

                    b.ToTable("tbl_PhieuDatHang");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuGiaoHang", b =>
                {
                    b.Property<string>("PkSMaPgh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaPGH");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.Property<string>("FkSMaPdh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaPDH");

                    b.Property<string>("SHoTenGh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sHoTenGH");

                    b.Property<string>("SSdtgh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sSDTGH");

                    b.HasKey("PkSMaPgh")
                        .HasName("PK__tbl_Phie__7A57CE2A2BC91673");

                    b.HasIndex("FkSMaNv");

                    b.HasIndex("FkSMaPdh");

                    b.ToTable("tbl_PhieuGiaoHang");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuNhapKho", b =>
                {
                    b.Property<string>("PkSMaPn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaPN");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.Property<string>("FkSMaPgh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaPGH");

                    b.HasKey("PkSMaPn")
                        .HasName("PK__tbl_Phie__DF6FEBCEF653D342");

                    b.HasIndex("FkSMaNv");

                    b.HasIndex("FkSMaPgh");

                    b.ToTable("tbl_PhieuNhapKho");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuThu", b =>
                {
                    b.Property<string>("PkSMaPt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaPT");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaKh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaKH");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.Property<string>("SHinhThucTt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sHinhThucTT");

                    b.HasKey("PkSMaPt")
                        .HasName("PK__tbl_Phie__DF6FEBC0E46C0696");

                    b.HasIndex("FkSMaKh");

                    b.HasIndex("FkSMaNv");

                    b.ToTable("tbl_PhieuThu");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuXuatKho", b =>
                {
                    b.Property<string>("PkSMaPx")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaPX");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.HasKey("PkSMaPx")
                        .HasName("PK__tbl_Phie__DF6FEBC4DF2AB2FE");

                    b.HasIndex("FkSMaNv");

                    b.ToTable("tbl_PhieuXuatKho");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuYeuCau", b =>
                {
                    b.Property<string>("PkSMaPyc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaPYC");

                    b.Property<bool?>("BTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangThai");

                    b.Property<DateTime?>("DTgLap")
                        .HasColumnType("datetime")
                        .HasColumnName("dTgLap");

                    b.Property<string>("FkSMaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNV");

                    b.HasKey("PkSMaPyc")
                        .HasName("PK__tbl_Phie__7A587871469C7019");

                    b.HasIndex("FkSMaNv");

                    b.ToTable("tbl_PhieuYeuCau");
                });

            modelBuilder.Entity("CNPM.Models.TblQuyen", b =>
                {
                    b.Property<string>("PkSMaQuyen")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaQuyen");

                    b.Property<string>("STenQuyen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sTenQuyen");

                    b.HasKey("PkSMaQuyen")
                        .HasName("PK__tbl_Quye__2C0839D82775F366");

                    b.ToTable("tbl_Quyen");
                });

            modelBuilder.Entity("CNPM.Models.TblSanPham", b =>
                {
                    b.Property<string>("PkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaSP");

                    b.Property<double?>("FDonGiaBan")
                        .HasColumnType("float")
                        .HasColumnName("fDonGiaBan");

                    b.Property<string>("FkSMaLoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaLoai");

                    b.Property<string>("FkSMaNcc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaNCC");

                    b.Property<int?>("ISl")
                        .HasColumnType("int")
                        .HasColumnName("iSL");

                    b.Property<string>("SDonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sDonViTinh");

                    b.Property<DateOnly?>("SHanDung")
                        .HasColumnType("date")
                        .HasColumnName("sHanDung");

                    b.Property<string>("STenSp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenSP");

                    b.HasKey("PkSMaSp")
                        .HasName("PK__tbl_SanP__DF6F443676EAB98E");

                    b.HasIndex("FkSMaLoai");

                    b.HasIndex("FkSMaNcc");

                    b.ToTable("tbl_SanPham");
                });

            modelBuilder.Entity("CNPM.Models.TblTaiKhoan", b =>
                {
                    b.Property<string>("PkSMaTk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_sMaTK");

                    b.Property<string>("FkSMaQuyen")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FK_sMaQuyen");

                    b.Property<string>("SMk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sMK");

                    b.Property<string>("STenTk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sTenTK");

                    b.HasKey("PkSMaTk")
                        .HasName("PK__tbl_TaiK__DF6F4C4AA6C26A13");

                    b.HasIndex("FkSMaQuyen");

                    b.ToTable("tbl_TaiKhoan");
                });

            modelBuilder.Entity("TblCtbaoCaoThuChi", b =>
                {
                    b.Property<string>("PkFkSMaBc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaBC");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.HasKey("PkFkSMaBc", "PkFkSMaSp")
                        .HasName("PK__tbl_CTBa__091FC2A60E2AC47B");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTBaoCaoThuChi", (string)null);
                });

            modelBuilder.Entity("TblCtphieuChi", b =>
                {
                    b.Property<string>("PkFkSMaPchi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaPChi");

                    b.Property<string>("PkFkSMaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaSP");

                    b.HasKey("PkFkSMaPchi", "PkFkSMaSp")
                        .HasName("PK__tbl_CTPh__B22F9ECD5305DE24");

                    b.HasIndex("PkFkSMaSp");

                    b.ToTable("tbl_CTPhieuChi", (string)null);
                });

            modelBuilder.Entity("TblThanhVienHuy", b =>
                {
                    b.Property<string>("PkFkMaBbh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_MaBBH");

                    b.Property<string>("PkFkSMaNguoiHuy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaNguoiHuy");

                    b.HasKey("PkFkMaBbh", "PkFkSMaNguoiHuy")
                        .HasName("PK__tbl_Than__8ADFC24EADBF51EA");

                    b.HasIndex("PkFkSMaNguoiHuy");

                    b.ToTable("tbl_ThanhVienHuy", (string)null);
                });

            modelBuilder.Entity("TblThanhVienKiemKe", b =>
                {
                    b.Property<string>("PkFkSMaBbk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaBBK");

                    b.Property<string>("PkFkSMaNguoiKiem")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PK_FK_sMaNguoiKiem");

                    b.HasKey("PkFkSMaBbk", "PkFkSMaNguoiKiem")
                        .HasName("PK__tbl_Than__B30ABB7373E087D0");

                    b.HasIndex("PkFkSMaNguoiKiem");

                    b.ToTable("tbl_ThanhVienKiemKe", (string)null);
                });

            modelBuilder.Entity("CNPM.Models.TblBaoCaoThuChi", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblBaoCaoThuChis")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_BaoCa__FK_sM__1BC821DD");

                    b.Navigation("FkSMaNvNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblBienBanHuy", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblBienBanHuys")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_BienB__FK_sM__06CD04F7");

                    b.Navigation("FkSMaNvNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblBienBanKiemKe", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblBienBanKiemKes")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_BienB__FK_sM__114A936A");

                    b.Navigation("FkSMaNvNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtbienBanHuy", b =>
                {
                    b.HasOne("CNPM.Models.TblBienBanHuy", "PkFkSMaBbhNavigation")
                        .WithMany("TblCtbienBanHuys")
                        .HasForeignKey("PkFkSMaBbh")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTBie__PK_FK__09A971A2");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtbienBanHuys")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTBie__PK_FK__0A9D95DB");

                    b.Navigation("PkFkSMaBbhNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtbienBanKiemKe", b =>
                {
                    b.HasOne("CNPM.Models.TblBienBanKiemKe", "PkFkSMaBbkNavigation")
                        .WithMany("TblCtbienBanKiemKes")
                        .HasForeignKey("PkFkSMaBbk")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTBie__PK_FK__14270015");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtbienBanKiemKes")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTBie__PK_FK__151B244E");

                    b.Navigation("PkFkSMaBbkNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCthopDongCungCap", b =>
                {
                    b.HasOne("CNPM.Models.TblHopDongCungCap", "PkFkSMaHdNavigation")
                        .WithMany("TblCthopDongCungCaps")
                        .HasForeignKey("PkFkSMaHd")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTHop__PK_FK__6D0D32F4");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCthopDongCungCaps")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTHop__PK_FK__6E01572D");

                    b.Navigation("PkFkSMaHdNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuDatHang", b =>
                {
                    b.HasOne("CNPM.Models.TblPhieuDatHang", "PkFkSMaPdhNavigation")
                        .WithMany("TblCtphieuDatHangs")
                        .HasForeignKey("PkFkSMaPdh")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__5629CD9C");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtphieuDatHangs")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__571DF1D5");

                    b.Navigation("PkFkSMaPdhNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuGiaoHang", b =>
                {
                    b.HasOne("CNPM.Models.TblPhieuGiaoHang", "PkFkSMaPghNavigation")
                        .WithMany("TblCtphieuGiaoHangs")
                        .HasForeignKey("PkFkSMaPgh")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__5DCAEF64");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtphieuGiaoHangs")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__5EBF139D");

                    b.Navigation("PkFkSMaPghNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuNhapKho", b =>
                {
                    b.HasOne("CNPM.Models.TblPhieuNhapKho", "PkFkSMaPnNavigation")
                        .WithMany("TblCtphieuNhapKhos")
                        .HasForeignKey("PkFkSMaPn")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__656C112C");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtphieuNhapKhos")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__66603565");

                    b.Navigation("PkFkSMaPnNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuThu", b =>
                {
                    b.HasOne("CNPM.Models.TblPhieuThu", "PkFkSMaPtNavigation")
                        .WithMany("TblCtphieuThus")
                        .HasForeignKey("PkFkSMaPt")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__02FC7413");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtphieuThus")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__03F0984C");

                    b.Navigation("PkFkSMaPtNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuXuatKho", b =>
                {
                    b.HasOne("CNPM.Models.TblPhieuXuatKho", "PkFkSMaPxNavigation")
                        .WithMany("TblCtphieuXuatKhos")
                        .HasForeignKey("PkFkSMaPx")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__7B5B524B");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtphieuXuatKhos")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__7C4F7684");

                    b.Navigation("PkFkSMaPxNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblCtphieuYeuCau", b =>
                {
                    b.HasOne("CNPM.Models.TblPhieuYeuCau", "PkFkSMaPycNavigation")
                        .WithMany("TblCtphieuYeuCaus")
                        .HasForeignKey("PkFkSMaPyc")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__4E88ABD4");

                    b.HasOne("CNPM.Models.TblSanPham", "PkFkSMaSpNavigation")
                        .WithMany("TblCtphieuYeuCaus")
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__4F7CD00D");

                    b.Navigation("PkFkSMaPycNavigation");

                    b.Navigation("PkFkSMaSpNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblHopDongCungCap", b =>
                {
                    b.HasOne("CNPM.Models.TblNhaCungCap", "FkSMaNccNavigation")
                        .WithMany("TblHopDongCungCaps")
                        .HasForeignKey("FkSMaNcc")
                        .HasConstraintName("FK__tbl_HopDo__FK_sM__693CA210");

                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblHopDongCungCaps")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_HopDo__FK_sM__6A30C649");

                    b.Navigation("FkSMaNccNavigation");

                    b.Navigation("FkSMaNvNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblNhanVien", b =>
                {
                    b.HasOne("CNPM.Models.TblChucVu", "FkSMaCvNavigation")
                        .WithMany("TblNhanViens")
                        .HasForeignKey("FkSMaCv")
                        .HasConstraintName("FK__tbl_NhanV__FK_sM__44FF419A");

                    b.HasOne("CNPM.Models.TblTaiKhoan", "FkSMaTkNavigation")
                        .WithMany("TblNhanViens")
                        .HasForeignKey("FkSMaTk")
                        .HasConstraintName("FK__tbl_NhanV__FK_sM__440B1D61");

                    b.Navigation("FkSMaCvNavigation");

                    b.Navigation("FkSMaTkNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuChi", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblPhieuChis")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__71D1E811");

                    b.HasOne("CNPM.Models.TblPhieuNhapKho", "FkSMaPnNavigation")
                        .WithMany("TblPhieuChis")
                        .HasForeignKey("FkSMaPn")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__70DDC3D8");

                    b.Navigation("FkSMaNvNavigation");

                    b.Navigation("FkSMaPnNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuDatHang", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblPhieuDatHangs")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__534D60F1");

                    b.HasOne("CNPM.Models.TblPhieuYeuCau", "FkSMaPycNavigation")
                        .WithMany("TblPhieuDatHangs")
                        .HasForeignKey("FkSMaPyc")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__52593CB8");

                    b.Navigation("FkSMaNvNavigation");

                    b.Navigation("FkSMaPycNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuGiaoHang", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblPhieuGiaoHangs")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__5AEE82B9");

                    b.HasOne("CNPM.Models.TblPhieuDatHang", "FkSMaPdhNavigation")
                        .WithMany("TblPhieuGiaoHangs")
                        .HasForeignKey("FkSMaPdh")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__59FA5E80");

                    b.Navigation("FkSMaNvNavigation");

                    b.Navigation("FkSMaPdhNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuNhapKho", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblPhieuNhapKhos")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__628FA481");

                    b.HasOne("CNPM.Models.TblPhieuGiaoHang", "FkSMaPghNavigation")
                        .WithMany("TblPhieuNhapKhos")
                        .HasForeignKey("FkSMaPgh")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__619B8048");

                    b.Navigation("FkSMaNvNavigation");

                    b.Navigation("FkSMaPghNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuThu", b =>
                {
                    b.HasOne("CNPM.Models.TblKhachHang", "FkSMaKhNavigation")
                        .WithMany("TblPhieuThus")
                        .HasForeignKey("FkSMaKh")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__00200768");

                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblPhieuThus")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__7F2BE32F");

                    b.Navigation("FkSMaKhNavigation");

                    b.Navigation("FkSMaNvNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuXuatKho", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblPhieuXuatKhos")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__787EE5A0");

                    b.Navigation("FkSMaNvNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuYeuCau", b =>
                {
                    b.HasOne("CNPM.Models.TblNhanVien", "FkSMaNvNavigation")
                        .WithMany("TblPhieuYeuCaus")
                        .HasForeignKey("FkSMaNv")
                        .HasConstraintName("FK__tbl_Phieu__FK_sM__4BAC3F29");

                    b.Navigation("FkSMaNvNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblSanPham", b =>
                {
                    b.HasOne("CNPM.Models.TblLoaiSanPham", "FkSMaLoaiNavigation")
                        .WithMany("TblSanPhams")
                        .HasForeignKey("FkSMaLoai")
                        .HasConstraintName("FK__tbl_SanPh__FK_sM__47DBAE45");

                    b.HasOne("CNPM.Models.TblNhaCungCap", "FkSMaNccNavigation")
                        .WithMany("TblSanPhams")
                        .HasForeignKey("FkSMaNcc")
                        .HasConstraintName("FK__tbl_SanPh__FK_sM__48CFD27E");

                    b.Navigation("FkSMaLoaiNavigation");

                    b.Navigation("FkSMaNccNavigation");
                });

            modelBuilder.Entity("CNPM.Models.TblTaiKhoan", b =>
                {
                    b.HasOne("CNPM.Models.TblQuyen", "FkSMaQuyenNavigation")
                        .WithMany("TblTaiKhoans")
                        .HasForeignKey("FkSMaQuyen")
                        .HasConstraintName("FK__tbl_TaiKh__FK_sM__412EB0B6");

                    b.Navigation("FkSMaQuyenNavigation");
                });

            modelBuilder.Entity("TblCtbaoCaoThuChi", b =>
                {
                    b.HasOne("CNPM.Models.TblBaoCaoThuChi", null)
                        .WithMany()
                        .HasForeignKey("PkFkSMaBc")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTBao__PK_FK__1EA48E88");

                    b.HasOne("CNPM.Models.TblSanPham", null)
                        .WithMany()
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTBao__PK_FK__1F98B2C1");
                });

            modelBuilder.Entity("TblCtphieuChi", b =>
                {
                    b.HasOne("CNPM.Models.TblPhieuChi", null)
                        .WithMany()
                        .HasForeignKey("PkFkSMaPchi")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__74AE54BC");

                    b.HasOne("CNPM.Models.TblSanPham", null)
                        .WithMany()
                        .HasForeignKey("PkFkSMaSp")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_CTPhi__PK_FK__75A278F5");
                });

            modelBuilder.Entity("TblThanhVienHuy", b =>
                {
                    b.HasOne("CNPM.Models.TblBienBanHuy", null)
                        .WithMany()
                        .HasForeignKey("PkFkMaBbh")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Thanh__PK_FK__0D7A0286");

                    b.HasOne("CNPM.Models.TblNhanVien", null)
                        .WithMany()
                        .HasForeignKey("PkFkSMaNguoiHuy")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Thanh__PK_FK__0E6E26BF");
                });

            modelBuilder.Entity("TblThanhVienKiemKe", b =>
                {
                    b.HasOne("CNPM.Models.TblBienBanKiemKe", null)
                        .WithMany()
                        .HasForeignKey("PkFkSMaBbk")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Thanh__PK_FK__17F790F9");

                    b.HasOne("CNPM.Models.TblNhanVien", null)
                        .WithMany()
                        .HasForeignKey("PkFkSMaNguoiKiem")
                        .IsRequired()
                        .HasConstraintName("FK__tbl_Thanh__PK_FK__18EBB532");
                });

            modelBuilder.Entity("CNPM.Models.TblBienBanHuy", b =>
                {
                    b.Navigation("TblCtbienBanHuys");
                });

            modelBuilder.Entity("CNPM.Models.TblBienBanKiemKe", b =>
                {
                    b.Navigation("TblCtbienBanKiemKes");
                });

            modelBuilder.Entity("CNPM.Models.TblChucVu", b =>
                {
                    b.Navigation("TblNhanViens");
                });

            modelBuilder.Entity("CNPM.Models.TblHopDongCungCap", b =>
                {
                    b.Navigation("TblCthopDongCungCaps");
                });

            modelBuilder.Entity("CNPM.Models.TblKhachHang", b =>
                {
                    b.Navigation("TblPhieuThus");
                });

            modelBuilder.Entity("CNPM.Models.TblLoaiSanPham", b =>
                {
                    b.Navigation("TblSanPhams");
                });

            modelBuilder.Entity("CNPM.Models.TblNhaCungCap", b =>
                {
                    b.Navigation("TblHopDongCungCaps");

                    b.Navigation("TblSanPhams");
                });

            modelBuilder.Entity("CNPM.Models.TblNhanVien", b =>
                {
                    b.Navigation("TblBaoCaoThuChis");

                    b.Navigation("TblBienBanHuys");

                    b.Navigation("TblBienBanKiemKes");

                    b.Navigation("TblHopDongCungCaps");

                    b.Navigation("TblPhieuChis");

                    b.Navigation("TblPhieuDatHangs");

                    b.Navigation("TblPhieuGiaoHangs");

                    b.Navigation("TblPhieuNhapKhos");

                    b.Navigation("TblPhieuThus");

                    b.Navigation("TblPhieuXuatKhos");

                    b.Navigation("TblPhieuYeuCaus");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuDatHang", b =>
                {
                    b.Navigation("TblCtphieuDatHangs");

                    b.Navigation("TblPhieuGiaoHangs");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuGiaoHang", b =>
                {
                    b.Navigation("TblCtphieuGiaoHangs");

                    b.Navigation("TblPhieuNhapKhos");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuNhapKho", b =>
                {
                    b.Navigation("TblCtphieuNhapKhos");

                    b.Navigation("TblPhieuChis");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuThu", b =>
                {
                    b.Navigation("TblCtphieuThus");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuXuatKho", b =>
                {
                    b.Navigation("TblCtphieuXuatKhos");
                });

            modelBuilder.Entity("CNPM.Models.TblPhieuYeuCau", b =>
                {
                    b.Navigation("TblCtphieuYeuCaus");

                    b.Navigation("TblPhieuDatHangs");
                });

            modelBuilder.Entity("CNPM.Models.TblQuyen", b =>
                {
                    b.Navigation("TblTaiKhoans");
                });

            modelBuilder.Entity("CNPM.Models.TblSanPham", b =>
                {
                    b.Navigation("TblCtbienBanHuys");

                    b.Navigation("TblCtbienBanKiemKes");

                    b.Navigation("TblCthopDongCungCaps");

                    b.Navigation("TblCtphieuDatHangs");

                    b.Navigation("TblCtphieuGiaoHangs");

                    b.Navigation("TblCtphieuNhapKhos");

                    b.Navigation("TblCtphieuThus");

                    b.Navigation("TblCtphieuXuatKhos");

                    b.Navigation("TblCtphieuYeuCaus");
                });

            modelBuilder.Entity("CNPM.Models.TblTaiKhoan", b =>
                {
                    b.Navigation("TblNhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
